apiVersion: v1
kind: PersistentVolume
metadata:
  name: miq-pv03
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/minishift/miq-server
  persistentVolumeReclaimPolicy: Recycle
