apiVersion: v1
kind: PersistentVolume
metadata:
  name: miq-pv04
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/minishift/miq-apache
  persistentVolumeReclaimPolicy: Recycle
